version: "3.9"

services:
  m3u_updater:
    image: python:3.11
    container_name: m3u_updater
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-input pyyaml >/dev/null 2>&1 || true; while true; do python /app/generate_m3u.py; sleep 600; done"
