name: Goals M3U Bot

on:
  workflow_dispatch:  # Manuel tetikleme
  schedule:
    - cron: "*/5 * * * *"  # Her 5 dakikada bir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Gerekli paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: goals.py çalıştır
        run: python goals.py

      - name: goals.m3u dosyasını repoya push et
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add goals.m3u
          git commit -m "Update goals.m3u [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
