name: Update M3U Files

on:
  schedule:
    - cron: "*/380 * * * *"   # Hər 10 dəqiqədən bir
  workflow_dispatch:          # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Run M3U generator
        run: |
          python generate_m3u.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add m3u_files/
          git commit -m "Auto-update M3U: $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push
